### ISSUE TITLE
Unable to read any data - UE 4.21

### ISSUE THREAD

**Issue by RisingSunStudios** [getnamo/socketio-client-ue4#111]
Hi there,
On Windows, UE 1.21.2 I'm not able to retrieve any data from the SIOJsonValue parameters on the "On Event" events.

![error_01](https://user-images.githubusercontent.com/39057393/53890574-5d4d7800-4020-11e9-9c2c-6f6ee8802923.PNG)
![error_02](https://user-images.githubusercontent.com/39057393/53890575-5de60e80-4020-11e9-8c35-b4aa85c76156.PNG)

No matter what json I try, I cannot retrieve the "Title" object from the json.

Here is the sample json:
```
{
    "Title": {
        "Text": "Chart Title",
        "Caption": "Chart Caption"
    }
}

```

I've followed the guide from [https://github.com/getnamo/socketio-client-ue4](url) but must be missing something. Originally I planned on using the "Json to Struct" functions but those failed with editor crashes, so back to first steps of trying to get something to parse correctly.

Any help appreciated.

**Comment by getnamo** [comment]
It appears your server is sending a string, not a json object, make sure you're not converting your objects to strings before sending!

If that can't be avoided, use _To JsonValue (String)_ node on your string and decode again.

**Comment by getnamo** [comment]
Just tested it, got same results when I stringified the json. So to recap, **don't** do this
![image](https://user-images.githubusercontent.com/542365/53914412-6cc5c480-4012-11e9-87c4-9a72f01a696f.png)

do this

![image](https://user-images.githubusercontent.com/542365/53914457-7e0ed100-4012-11e9-8758-c2f8666679cb.png)

If you're using a server which can't send raw objects, then you can get around this problem by **Value From Json String**. Everything else should work as expected.

![image](https://user-images.githubusercontent.com/542365/53914554-b2828d00-4012-11e9-94ab-ce4deaba6380.png)

**Comment by getnamo** [comment]
Just tested the json string to struct path and it doesn't crash for me, just spits out a warning
```LogJson: Error: Json Value of type 'String' used as a 'Object'.```
So I'd be curious what you tried for that and any crash logs from it.

If you do send the raw object from your server, here's how to setup your object as blueprint structs so that it decodes correctly:
_main struct_
![image](https://user-images.githubusercontent.com/542365/53915381-a39cda00-4014-11e9-9dc3-2c3b14de2eb2.png)
It has a single variable which is called Title (matching your json property) and it's of type sub-struct (I named it _Issue111SubStruct_, but it can be called anything)

sub-struct:
![image](https://user-images.githubusercontent.com/542365/53915336-8f58dd00-4014-11e9-877f-28efe0a8c40d.png)
has two string fields _Text_ and _Caption_

Then this is how the round trip test is done
![image](https://user-images.githubusercontent.com/542365/53915711-510fed80-4015-11e9-8744-4be48c62d7dd.png)

Note that you only need the first box if you was to decode it, second box is just to test the conversion. The _Reply Struct_ is an actor member variable of type _Issue111Struct_

There is also an alternative way to structure your blueprint struct if you know all sub-members will be String:String mapped variables (blueprints can only have maps of same type).

![image](https://user-images.githubusercontent.com/542365/53916059-0b9ff000-4016-11e9-8e5a-c456e4153403.png)

Note that you may need to clear the _Title_ map on your _Issue111Alt_ Struct before setting or it may contain duplicates of the old variable when setting multiple times.

**Comment by RisingSunStudios** [comment]
Sorry for not getting back sooner, thanks for the thorough replies! Looks like its entirely user-error so I'll go ahead and close as its working as expected.

Thanks!
