### ISSUE TITLE
How to fetch data from server?

### ISSUE THREAD

**Issue by qb0813** [getnamo/socketio-client-ue4#119]
I execute a sql query in node.js and I want ue4 get the select results.
thanks.

**Comment by getnamo** [comment]
You probably want ```Emit with Callback``` (see here: https://github.com/getnamo/socketio-client-ue4#emit-with-callback). 

![emitwcallback](https://camo.githubusercontent.com/2d8364ce3642461051f0510581f1127c194dd1f6/687474703a2f2f692e696d6775722e636f6d2f456430314a71302e706e67)

In this case I'd probably name the event something like ```sqlQuery``` instead of echo.

You can emit any type of data, either generic types like a string or e.g. a [json object](https://github.com/getnamo/socketio-client-ue4#simple-json). If you can organize your data in structs, I'd highly recommend using that method.
![struct to json](https://camo.githubusercontent.com/74d6a8155a78c98be3777a036a4d0a48d3d915a3/687474703a2f2f692e696d6775722e636f6d2f637a69304149462e706e67)

Then you bind the callback to a function in your blueprint as shown. The name of the function should match the name given in ```Callback Function Name```.

![callback](https://camo.githubusercontent.com/0e205b51dc669c6a0d9ffe0c60f77c7edeb1d59d/687474703a2f2f692e696d6775722e636f6d2f5051696e4459792e676966)

On the server side you'd do something like

```javascript
//assuming you're using https://www.npmjs.com/package/mysql
const mysql = require('mysql');
const con = mysql.createConnection({
	host: "localhost",
	user: "yourusername",
	password: "yourpassword",
	database: "mydb"
});

socket.on('sqlQuery', function(queryData, callback){

	//we assume you pass a json with 
	//{"column": "*", "table": "users", "condition":"User=Bob"}

	//run the query
	con.query("SELECT" + queryData.column + " FROM " + queryData.table + " WHERE " + queryData.condition, function (err, result, fields) {
		if (err) throw err;
		console.log(result);

		//callback with result to ue4
		callback(result);
	});
});
```

**Comment by qb0813** [comment]
thanks a lot,I have got my problems solved.
