### ISSUE TITLE
Namespace cpp 

### ISSUE THREAD

**Issue by doganarif** [getnamo/socketio-client-ue4#164]
Can you explain how to use namespaces on cpp ?

**Comment by getnamo** [comment]
Functions the same way as in blueprint, use https://github.com/getnamo/socketio-client-ue4#namespaces for guidance. There is an optional namespace parameter in OnNativeEvent and Emits, (see e.g. https://github.com/getnamo/socketio-client-ue4#how-to-use---c for detailed c++ documentation) 

*OnNativeEvent (Bind Event in BP)*
https://github.com/getnamo/socketio-client-ue4/blob/master/Source/SocketIOClient/Public/SocketIOClientComponent.h#L380
```c++
SIOClientComponent->OnNativeEvent(FString("MyEvent"), [](const FString& Event, const TSharedPtr<FJsonValue>& Message)
{
	//Called when the event is received. We can e.g. log what we got
	UE_LOG(LogTemp, Log, TEXT("Received: %s"), *USIOJConvert::ToJsonString(Message));
}, TEXT("/MyNamespace"));
```

and e.g. 

*EmitNative (Emit in BP)*
https://github.com/getnamo/socketio-client-ue4/blob/master/Source/SocketIOClient/Public/SocketIOClientComponent.h#L261

```c++
//emit a float to a given namespace
SIOClientComponent->EmitNative(FString("nativeTest"), 9000.f, TEXT("/MyNamespace"));
```

and since 1.2.3 you can also join/leave namespaces without using events/emits with https://github.com/getnamo/socketio-client-ue4/blob/master/Source/SocketIOClient/Public/SocketIOClientComponent.h#L152 and https://github.com/getnamo/socketio-client-ue4/blob/master/Source/SocketIOClient/Public/SocketIOClientComponent.h#L158

Note that this same functionality exists on the non-uobject variant, FSocketIONative.

**Comment by Sere1** [comment]
i'm using  FSocketIONative. How can we use namespaces with on event ?
