### ISSUE TITLE
Bind Event to function on Network Thread results in the editor crashing

### ISSUE THREAD

**Issue by sleoniy** [getnamo/socketio-client-ue4#174]
It has come to my attention that running on Networking Thread results in crashing the whole editor. I am not doing anything special either in BP, just connecting to socket, binding event to function, and in the function I am printing what is being received.  

At 10,000 records, no crash, but at 20,000 crash. I am assuming this is why you mentioned that this thread is not safe with a lot of blueprint use. Since this is the case, what would be the work around for this? My overall goal is to receive records and pass them to a callback to update a text renderer.

In addition, for future reference, are you considering adding the functionality to generate an entirely new thread, aside from just Game & Network Thread?

EDIT: Adding screenshot of exception thrown
![image](https://user-images.githubusercontent.com/14221746/69551280-6c87a380-0f6a-11ea-827b-6e7d339648ca.png)

Thanks again for your time and your work! It is greatly appreciated :)

**Comment by getnamo** [comment]
Appears you may be accessing an element in an array after it was changed. If you do work on background threads with many calls it's important to copy the data you receive into another variable and then work on it if you re-use that event shortly after (because you may not finish processing something before it's overwritten again).

Regarding other threads. All sio networking happens on the network thread so this is the lowest latency state you receive an event. If you need to do parsing on another thread you can use the blueprint multithreading utility functions (https://github.com/getnamo/socketio-client-ue4#blueprint-multithreading) to pass your work to another background thread e.g. the taskgraph system. Keep in mind that if you use graph/member variables they will be shared between calls so you need to be careful of how you handle data flow there too. 

If you can't achieve your target performance with blueprint functions I suggest you drop down into c++ which has more fine-grained control over threading.

**Comment by sleoniy** [comment]
Morning Getnamo,

Cant stress to you how thankful I am for your in-depth responses. Below are screenshots of my blueprints. You will be able to see that I am not storing any of the data received anywhere. 

![image](https://user-images.githubusercontent.com/14221746/69651836-b2ae3700-103e-11ea-8af4-97c79870f44b.png)

My "OnEventRecv" Function:

![image](https://user-images.githubusercontent.com/14221746/69651936-d8d3d700-103e-11ea-927d-11a03ea41902.png)

Perhaps, printing may not be thread safe I will investigate this. My worst case plan was to develop C++, but since I do not have much C++ experience I was hoping BP would suffice lol. Thanks again!

**Comment by getnamo** [comment]
What happens if you put a delay node with 0 time between on event recv and print string? 
A latent action like delay causes it to be processed on the game thread. I'm just curious if the crash changes

**Comment by sleoniy** [comment]
Hey Getnamo,

I think its a great idea to try with a delay of 0. In addition to logs, will send that over as soon as possible. Thank you again for your assistance :)

**Comment by sleoniy** [comment]
Just an update - What I am doing now is when I receive an event, I am storing that in an array. On Game Thread, I will be handling the visualization rendering. I noticed that by using Print String, it would make my game crash. My overall purpose for this project is to be able to constantly stream data and have users interact with this data, which I am now able to do because of your assistance.

Just want to say thank you so much for your rapid and in-depth responses as it truly strengthen my understanding of UE & your plugin!
