### ISSUE TITLE
Possible Wrong Order of Blueprint Function/Event Pins

### ISSUE THREAD

**Issue by Neur1n** [getnamo/socketio-client-ue4#194]
When I try to bind a custom event to OnEvent (as shown in the first picture below), the generated custom event node (the second picture below) has to pins: `Event` and `Message Json`. However, what I get from the `Event` pin is the expected Json message, while the `Message Json` gives nothings.

![image](https://user-images.githubusercontent.com/17579247/78110605-d4c12700-742d-11ea-8121-051dcfdc7ffd.png)

![image](https://user-images.githubusercontent.com/17579247/78110702-0a661000-742e-11ea-9603-4938cb1adcb8.png)

Then I create a function with to inputs same as the custom event, and use `Bind Event to Function`:

![image](https://user-images.githubusercontent.com/17579247/78111442-3d5cd380-742f-11ea-89df-35e2fef42779.png)

This time, what I get from the `Event` is again the expected Json message, while the `Message Json` gives me the function name, i.e. "ProcessCmd".

I've tried to swap the pins, but it crashed UE4.

**Comment by getnamo** [comment]
There are two different bind functions depending on where you want to receive the event. ```Bind Event``` to bind it to be received in the generic ```On Event``` and ```Bind Event to Function``` to receive it to a specified function (or custom event).

For ```Bind Event``` variant you should follow https://github.com/getnamo/socketio-client-ue4#how-to-use---bp-basics

For bind event to function, it doesn't emit the event name since it is assumed you know which socketio event it is by the use of a custom function. So it should simply expect the overloaded SIOJsonValue or specific value types directly if you know them (avaliable since v0.6.8). See https://github.com/getnamo/socketio-client-ue4#binding-events-to-functions for specifics, it has the same function API as emit with callback which has a few more details https://github.com/getnamo/socketio-client-ue4#emit-with-callback.

**Comment by getnamo** [comment]
Clarified the readme a bit for https://github.com/getnamo/socketio-client-ue4#how-to-use---bp-basics. You won't have 'OnGenericEvent' yet (it's synonymous with 'OnEvent' used in earlier versions), that name change will come in a future release.

**Comment by Neur1n** [comment]
Your explanation is much appreciated, but I'm not sure about this:

>So it should simply expect an SIOJsonValue for any data or specific value types directly if you know them

Please allow me to post more screenshots.

In the first picture below, the input pins of the function is following the generated custom events as mentioned before, and notice the "Text Color" of the two printings.

In the second picture below, you will see that the blue printing which from the `MessageJson` pin is "ProcessCmd" (i.e. the function name) and the red printing which from the `Event` pin is "{"id": 1}" (i.e. a Json format string).

![image](https://user-images.githubusercontent.com/17579247/78204639-9d558780-74cc-11ea-8e5b-6ec2896b509d.png)
![image](https://user-images.githubusercontent.com/17579247/78204997-ad219b80-74cd-11ea-85ba-3fe5f58ce9a8.png)

**Comment by getnamo** [comment]
I believe what's happening is you're mismatching types which is causing the SIOJsonValue to match as a string in https://github.com/getnamo/socketio-client-ue4/blob/master/Source/SocketIOClient/Private/SocketIOClientComponent.cpp#L302 and then it returns the leftover variable in the stack making it appear like they've swapped. Do this: remove the event pin from your function and just pass in the message json and it will properly fill (also don't use get display name, but use as string or encode string, the string autocast picks the wrong type due to order of precedence)

**Comment by Neur1n** [comment]
> also don't use get display name

It was my fault. I literally didn't notice that. 🤦‍♂️
And after I remove the `Event` pin, the `MessageJson` pin gives me the expected messages. As you say "mismatching types", what could be wrong? Is it related to the emitter? (On the server side, messages are emitted by `server.emit('ue4', msg)`.)

If it is related to the server side, I understand it is not your responsibility. But a little hint would be much appreciated.

**Comment by getnamo** [comment]
It's not a server side thing, it's just that in the plugin when you write your receiving function you have the option of using SIOJsonValue for any data or one of the following direct parameters: 

-SIOJsonObject
-String
-Float
-Int
-Bool
-Byte Array

If one of those is used, it will auto-cast (and in the case of string, auto-convert) the first parameter to that variable. This is to reduce boilerplate for common types. What happened was you mixed up Bind Event and Bind Event to Function, using the bind event to function for the bind operation, but then using the Bind Event signature for the function signature (with a string event as first parameter). When the event was then triggered, it found your first parameter was a string and auto-converted your msg into it and then did nothing to your second parameter (get display name was just showing the UObject's Name).

The normal way is for all receiving functions to have just SIOJsonValue signature which can handle all types. The auto-casting is just a convenience boilerplate reduction for common types. Hope that clarifies things a little bit :), there's just a bit too much voodoo behind some of the conversion :p.

**Comment by Neur1n** [comment]
Thanks a lot!
