### ISSUE TITLE
Socketio animations

### ISSUE THREAD

**Issue by Sere1** [getnamo/socketio-client-ue4#195]
How can i send animatons to other clients with sockets ?

**Comment by getnamo** [comment]
That sounds like a very generic question. 

General architecture would be: 

1) serialize animation into either a struct or a binary format
2) emit that struct/binary to server that echoes it back to other clients
3) on other clients receive and deserialize the data back into whatever animation format you support.

This most likely won't work for static animation formats the engine uses, but you can probably pack those into .paks in the editor and use pak loading, e.g. https://www.unrealengine.com/marketplace/en-US/product/pak-loader-plugin or built-in c++ to unpak it into your game. Otherwise you'll need a custom animation format that can be runtime loaded ( maybe something like: https://forums.unrealengine.com/development-discussion/engine-source-github/122169-plugin-runtime-mesh-loader?).
