### ISSUE TITLE
Won't run on Oculus Quest

### ISSUE THREAD

**Issue by johnroper100** [getnamo/socketio-client-ue4#196]
I'm trying to use this plugin for an Oculus Quest game. The blueprint code works fine when I run it on my computer and it connects to my external socket server, but it doesn't work when on my oculus quest. I know it isn't an IP issue because the server is external and I can connect to it on other devices, and even on the Quest's web browser, just not in the game.

**Comment by johnroper100** [comment]
Fixed it, didn't hhacke packing correct

**Comment by pvharmo** [comment]
@johnroper100 How did you solve it? I'm having the same issue.

**Comment by nateainsworth** [comment]
We have been having the same issue here if anyone has a fix please can you post it. It works when running while connected to the PC. However, once you build the project onto the Oculus Quest 2 and run it natively it fails to connect to the socket. I'm assuming this could be due to the secure connection requirements of android and SSL. What would others recommend trying?

**Comment by jorgearroyop** [comment]
I'm having the same problem. I'm using Unreal 5.4.4 and SocketIOClient-Unreal v2.8.
I have already enabled on Unreal Platform Android the following settings: android.permission.INTERNET, android.permission.ACCESS_NETWORK_STATE and android:usesCleartextTraffic="true".

I have also tested locally with a Python http server and with an https server (with self signed certificate). 

Everything works fine when running on the Unreal Engine Editor but as soon as I build the package it doesn't work on the Meta Quest 3.

If someone has found a solution please share it :)
