### ISSUE TITLE
4.26 Update Tracker

### ISSUE THREAD

**Issue by getnamo** [getnamo/socketio-client-ue4#246]
Working build branch https://github.com/getnamo/socketio-client-ue4/tree/feature-UE4.26 merged into master. Pending a few fixes/enhancements before making a release.

**Comment by getnamo** [comment]
merged in https://github.com/getnamo/socketio-client-ue4/commit/f7ccd3ce154932e5f74ad7f8933fd862f50a3f41

**Comment by finger563** [comment]
The changes you've made for 4.26 compatibility are not backwards compatible for 4.25 - Specifically the calls to
```c++
((FTextureResource*)UpdateData->Texture2D->Resource)->GetTexture2DRHI(),
```
should be
```c++
((FTextureResource*)UpdateData->Texture2D->Resource)->TextureRHI->GetTexture2D(),
```

There are others (related to `TSharedRef`) which are also incompatible with 4.25. I'm working on a fork and will submit a PR soon so that the code is compatible between 4.25 and 4.26.

**Comment by getnamo** [comment]
If you make a pull request I'll merge it

**Comment by finger563** [comment]
PR opened in #248

**Comment by getnamo** [comment]
Early marketplace release: https://github.com/getnamo/socketio-client-ue4/releases/tag/v1.5.0mp
