### ISSUE TITLE
4.27 Support

### ISSUE THREAD

**Issue by namxam** [getnamo/socketio-client-ue4#287]
I saw, that you have a branch for 4.27 with a commit. Are you planning to release a new version any time soon?

**Comment by vagnaros** [comment]
I certainly hope so.... I've been using SIO for some time now; rebooting one of my old projects and no support for my current engine version. Serious bummer. The lack of UE4.27 support has brought my team and project to a stand still. Forget about UE5 for now and bring support for UE4.27 rather than coding for something that is not even close to a full release state and risking all your time and effort having to rewrite and rewrite and rewrite for a WIP engine.

Please bring support to 4.27!

**Comment by vagnaros** [comment]
UPDATE: I downloaded the 4.27 branch, after a day of fiddling with it, I found the thirdparty folder was empty.... I took the latest stable release for 4.26 and copy pasted the missing folders.... Built, and Loaded into Unreal Editor successfully.

I'll give the devs the chance to actually make it how they intended, so I'll keep my workaround version for personal use, but anybody that needs a working socketio version now for 4.27 that is my solution.

Cheers!

**Comment by getnamo** [comment]
I'll try to address 4.27 within next ~week, it should I suspect be largely code compatible with 4.26, but some fixes are needed for v1.6 for Linux & other platforms.

**Comment by CodiBasti** [comment]
@getnamo 
Hi Jan,
is it still your plan to update the plugin to 4.27?
We tried to compile 4.26 for 4.27 ourselves. We fixed some renamed functions, which is looking good. But now we are getting some of these:

`"SIO_TLS "is not defined as a preprocessor macro, replacing with '0' for 'directives'`
the same for "DEBUG" macro.

Any ideas how to solve this? Thank you for your work, we love the plugin!
Cheers

**Comment by getnamo** [comment]
The ue5 branch was already compiling for v4.27 largely unchanged. 

Finally got around to testing a release for various platforms and the basic tests passed and a 4.27 release is now available here: https://github.com/getnamo/socketio-client-ue4/releases/tag/v1.8.0

**Comment by CodiBasti** [comment]
@getnamo 
You are the man!
