### ISSUE TITLE
Component tries to connect to server even in editor

### ISSUE THREAD

**Issue by nomako** [getnamo/socketio-client-ue4#47]
Every time when I open blueprint with **SocketIOComponent** in it, **SocketIOComponent** is trying to connect to server.
Moreover, SocketIOComponent events also will be called...
If you disable **bShouldAutoConnect** parameter, it will not connect but still create **FSocketIONative** object.

**Comment by getnamo** [comment]
We can add a toggle to check at init which world the component is in and and if you have it set to game world only then it will ignore editor instantiation. Otherwise components do get initialized in editor world whenever you open a blueprint with the component. There should be no leaks however as it closes when the blueprint or editor world gets destroyed. 

If we set the toggle and default it to game world only it should cover the most common expectation. I'm trying to think of a use case where you'd want to connect in editor world... there probably is one.

**Comment by LordNed** [comment]
If you move
```	if (bShouldAutoConnect)
	{
		Connect(AddressAndPort);	//connect to default address
	}```
from InitializeComponent to BeginPlay, BeginPlay is not called until you actually start the server. This means that adding the component will not attempt to connect to the server. This should be the more official fix that doesn't involve trying to check what type of world it is in.
