### ISSUE TITLE
"As string" fails to serialize the message JSON object

### ISSUE THREAD

**Issue by ashah28** [getnamo/socketio-client-ue4#64]
Hello developers,

It seems the "As string" blueprint node is failing to convert the JSON message to string.

For all the combinations I have tried, I get the following in the output log:
**LogJson: Error: Json Value of type 'Object' used as a 'String'.**

Attaching the combinations that I tried and failed:
![2017-11-02 13_44_05-firstpersoncharacter_](https://user-images.githubusercontent.com/21695894/32349584-c3f49322-bfd4-11e7-9912-3bc9017fa188.png)
![2017-11-02 13_45_36-firstpersoncharacter_](https://user-images.githubusercontent.com/21695894/32349585-c40c9666-bfd4-11e7-9cf2-bcf199050d8c.png)

My approach was almost the same as the third image in the project's home page(https://github.com/getnamo/socketio-client-ue4):
![687474703a2f2f692e696d6775722e636f6d2f76566c4e426c782e706e67](https://user-images.githubusercontent.com/21695894/32349697-2facdb56-bfd5-11e7-965a-f601ad253774.png)

Apparently, the data format from the socket seems correct as the following blueprint works fine:
![2017-11-02 13_49_50-firstpersoncharacter_](https://user-images.githubusercontent.com/21695894/32349589-c87821ca-bfd4-11e7-9265-f29fe89739e0.png)

Response that I am sending from the server:

emit('connection response', {'data': 'Connected'}) where,
'connection response' is the event and 
'{'data': 'Connected'}' is the JSON message

UE version: 4.17.1

Thank you.

**Comment by getnamo** [comment]
You're getting this error because your JSON type is an object not a string. The function _As String_ tries to interpret a json value to a string, since it is not it is throwing that error.

What you want to do however is to convert an SIOJson Value or Object to it's JSON string representation. To do this you need to use the function _EncodeJsonString_ instead. 

I believe the documentation is a bit hazy on this and it may be good to have an implicit conversion from the _As String_ function. I guess that depends on whether UE4 developers prefer explicit typing or more javascript like duck typing behavior.

**Comment by getnamo** [comment]
Decided to add auto-conversion by default here: https://github.com/getnamo/socketio-client-ue4/commit/2b118c4ca27eef923b93dc15f97fca00fd448753

Will sweep up other issues before making a 4.18 release however.

**Comment by ashah28** [comment]
Sure, Thanks for the enhancement.
