### ISSUE TITLE
Keep connection between levels? (old: ActorComponent ??)

### ISSUE THREAD

**Issue by Monstreur** [getnamo/socketio-client-ue4#69]
Hi,
I've got a problem :
I need to travel between levels but i want to keep the connection.
I also want to connect on port 3000 the client and the server on port 3001.
But i can't because it's an actorComponent so when i travel, it reinitialise the connection.

**Comment by getnamo** [comment]
Support for this was added in 0.7 (see change notes: https://github.com/getnamo/socketio-client-ue4/releases/tag/0.7.0).

All you do is tick plugin scoped connection on your actor component in class defaults and the next actor component will pickup the same connection with the same plugin scope id ('default' if you leave it unchanged). I've added a small section in the readme on this feature: https://github.com/getnamo/socketio-client-ue4#plugin-scoped-connection.

You can also pick any port when you connect, but to my knowledge without a proxy you cannot have asymmetric ports.

**Comment by getnamo** [comment]
Also if you want a custom connection type that isn't an actor component, you'll have to switch to C++ and use FSocketIONative, which supports manual allocation and does not depend on UObjects or AActors. The ```SocketIOClientComponent``` uses this internally and you can see example code of it's use in the class implementation: https://github.com/getnamo/socketio-client-ue4/blob/master/Source/SocketIOClient/Private/SocketIOClientComponent.cpp

**Comment by getnamo** [comment]
Also refer to https://answers.unrealengine.com/questions/384707/when-can-actors-exist-between-levels.html on how to maintain actors between level transitions.

**Comment by Monstreur** [comment]
Okay i take a look at all your links, but i just want to know : Why do you made it as an ActorComponent ? To be dependant on Map end and Map start ? Just for that ?
I'm little bit curious but it's also to consider it for my custom implementation.

**Comment by getnamo** [comment]
Actor components are very easy to add or remove to a blueprint actor of choice and they give easy multicast delegate support in blueprint. By having it attached to a world you can also ensure that connection and disconnection can happen automatically, shrinking the amount of code necessary to get something working. Despite these default behaviors, you have the full flexibility to toggle settings on or off to fit your needs.

Largely this is nearly ideal architecture for blueprint use, since blueprint memory is managed and largely related to levels/worlds. The only downside of this setup is non-ideal level transitioning, but if you want to manage that, you can use a plugin scoped connection or drop down to C++ which is the more appropriate language for custom allocation or things existing outside the garbage collected memory.

Also socket.io connections are lightweight, you could consider storing some string data and pass it on to the next world to allow the next connection to pickup data without using any plugin scoped connections.

Though I don't doubt that there will always be some use cases that fall out of this architecture. Suggestions are always welcome.

**Comment by Monstreur** [comment]
Okay, i trust you and believe that you did the best way to implement socket.io. So i will not make my own, but i remembered that i use a sessionKey when connect to server. I'll keep it in client info in an object, and retrieve it to give it when send event. So i will identifiy clients with it.
This will fix my problem because no matter my connection disconect or connect multiple times, with dfferent socket.id, it will keep the reference to the player.
Is there a way to pass it (just a SHA512 key string) when user connect (on connection event)

**Comment by getnamo** [comment]
There might be a better way to have always live connections, maybe through replacing the online subsystem, but I haven't hit a personal use case for it that can't be worked around using actors reconnecting. You can also use a persistent level and stream load/unload sub-levels which would maintain your connection in the persistent level since its actors wouldn't unload.

That connection token idea you have is largely how I would approach the problem.  You can pass in e.g. an auth token string using the connect function (disable auto-connect on your component) as a query or header, see example found in the readme
https://github.com/getnamo/socketio-client-ue4#complex-connect. You can also check out the other issue https://github.com/getnamo/socketio-client-ue4/issues/70 for an example of how another user is trying to pass in an auth token.

Regarding encryption, openssl is currently not compiled in. In theory the underlying library does support ssl (https://github.com/socketio/socket.io-client-cpp) but it would require rebuilding the library with that option correctly linked. See the issue https://github.com/getnamo/socketio-client-ue4/issues/39 for that problem. You can also just build your own encryption on top, but it may be saner to help build openssl into the C++ library.
