### ISSUE TITLE
How to parse json ?

### ISSUE THREAD

**Issue by lucaspojo** [getnamo/socketio-client-ue4#88]
Hi ! 

I need to receive position of other player from Nodejs server.

I try this : ![bp](https://image.prntscr.com/image/fORulLfnRySHpWGuT4AjvA.png)

But the value is empty. how to fix ? thx 👍 

Nodejs code : 
`

    socket.on('playerMove', function(location){

        playerLocation[socket.id] = {'x':location.myArray[0],
                                     'y':location.myArray[1],
                                     'z':location.myArray[2]}
                                     
        socket.emit('playerPosition', playerLocation[socket.id]);

    })
`

**Comment by getnamo** [comment]
Bind event should be called in a setup stage, e.g. on begin play. The way you you have it set it will never receive the data because the event isn't bound before the event gets called externally, so the plugin doesn't know where to forward it to.
![](https://camo.githubusercontent.com/eab6a40ab7c42e3f788ba45b36d879856ebf68b9/687474703a2f2f692e696d6775722e636f6d2f645778436d76512e706e67)

Then when that event gets called, the ```On Event``` (or a bound function) will receive that event. Filter it with an if statement to ensure you got the right event,

![](https://camo.githubusercontent.com/07876d1bdcd2e43fdace023f4d7e16336bde1788/687474703a2f2f692e696d6775722e636f6d2f76566c4e426c782e706e67)


 or if you have a lot of events, consider binding to function https://github.com/getnamo/socketio-client-ue4#binding-events-to-functions.

**Comment by lucaspojo** [comment]
Message Json -----> JsonObjectToStruct   crash unreal engine every time.

and if i try tu print the Message Json directly, i get : SIOjsonObject_100.

There is no simple example for get json value ?? 

Thx.

**Comment by getnamo** [comment]
You can do ```To String``` or ```EncodeJson``` from SIOJsonObject to see what your json encoded data looks like, from there you need to match your struct type to decode directly into struct. If that's still giving your trouble, you have the option of decoding it manually using field types, again see https://github.com/getnamo/socketio-client-ue4#decoding-responses for an example. The readme on the main repo (https://github.com/getnamo/socketio-client-ue4/blob/master/README.md) is really thorough and you should be able to follow each part to get your use case working 

![](https://camo.githubusercontent.com/cf80a49292b03219fb3fa2dadef7e2f88d39acb6/687474703a2f2f692e696d6775722e636f6d2f757241683254482e706e67)

There's also a fully working example with server code found at https://github.com/getnamo/socketio-client-ue4-example
